---
title: "Data Import"
output: github_document
---

```{r}
library(tidyverse)
library(readxl)
library(haven)
```

Let's import a dataset

```{r}
litters_df =
  read_csv("data/FAS_litters.csv")
```

always look at your data!

```{r}
names(litters_df)
```

Update the names in "litters_df"
```{r}
litters_df=
  janitor::clean_names(litters_df)
```


Look at the data

```{r}
litters_df
```

Sometimes skimming data is neat?
```{r}
skimr::skim(litters_df)
```


## Fix the missingness
```{r}
litters_df=
  read_csv("data/FAS_litters.csv", na = c("NA",".",""))
```

## import pups data
```{r}
pups_df=
    read_csv("data/FAS_pups.csv", na = c("NA",".",""),skip = 3)

pups_df = 
  janitor::clean_names(pups_df)
```

## Okay what about Excels

CSVs are really great but sometimes you get an Excel File.

```{r}
mlb_df =
  read_excel("data/mlb11.xlsx")
```

Import LotR word counts.
```{r}
fotr_df = 
  read_excel("data/LotR_Words.xlsx", range = "B3:D6")
```

## SAS??????

Import pulse data
```{r}
pulse_df =
  read_sas("data/public_pulse_data.sas7bdat")

pulse_df = 
  janitor::clean_names(pulse_df)
```


## Why do I hate read.csv so much??
```{r,eval = FALSE}
litters_df_base =
  read.csv("data/FAS_litters.csv")
```

## What about data exporting?

```{r}
write_csv(fotr_df,"data/fotr.csv")
```










