---
title: "Data Manipulation"
author: "Bohan Zhu"
date: "2025-09-18"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

Let's first import the datasets
```{r}
litters_df=
  read_csv("data/FAS_litters.csv", na = c("NA",".",""))

litters_df=
  janitor::clean_names(litters_df)

pups_df=
    read_csv("data/FAS_pups.csv", na = c("NA",".",""),skip = 3)

pups_df = 
  janitor::clean_names(pups_df)

pups_df = 
  janitor::clean_names(pups_df)
```

## `select`

`select` selects variables from my dataframe.

select specific
```{r}
select(litters_df, group, litter_number, gd0_weight)
```

select a range
```{r}
select(litters_df, group:gd_of_birth)
```

select by removal
```{r}
select(litters_df,-group)
select(litters_df, -(group:gd_of_birth))

```

select by preflix

```{r}
select(litters_df,group, starts_with("gd"))
```

rearrange by selecting
```{r}
select(litters_df,starts_with("gd"),group)
select(litters_df,litter_number,everything())

relocate(litters_df,litter_number)
```

rename by selecting
```{r}
select(litters_df,GROUP = group, everything())

rename(litters_df,GROUP = group)
```

What if i only select one variable..?
```{r}
select(litters_df,group)

# is not same as pull or $. will that two everything out but not as a character.
```
LA code:
```{r}
select(pups_df,litter_number:pd_ears)
```





